name: Send Slack Daily Report

on:
  schedule:
    - cron: "32 17 * * 1-5"

jobs:
  send_slack_message:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack message
        uses: slackapi/slack-github-action@v1.24.0
        with:
          "text": "데일리 보고"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          CHANEEL_ID: ${{secrets.CHANNEL_ID}}

        if: always()
