name: Send Slack Daily Report

on:
  schedule:
    - cron: "03 17 * * 1-5"

jobs:
  send_slack_message:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack message
        uses: 8398a7/action-slack@v3.16.2
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          CHANEEL_ID: ${{secrets.CHANNEL_ID}}
        run: |
          node -e "
          const { WebClient } = require('@slack/web-api');
          const client = new WebClient(process.env.SLACK_BOT_TOKEN);
          const channelId = process.env.CHANNEL_ID;

          const today = new Date().toLocaleString('ko-KR', { timeZone: 'Asia/Seoul', dateStyle: 'full' });
          const year = today.getFullYear();
          const month = String(today.getMonth() + 1).padStart(2, '0');
          const day = String(today.getDate()).padStart(2, '0');
          const formattedDate = `${year}-${month}-${day}`;


          const message = `${formattedDate} 데일리 보고`;

          client.chat.postMessage({
            channel: channelId,
            text: message,
          })
          .then(() => console.log('메시지 전송 완료'))
          .catch((error) => {
            console.error('오류가 발생했습니다:', error);
          });
          "
