name: Send Slack Daily Report

on:
  schedule:
    - cron: "14 17 * * 1-5"

jobs:
  send_slack_message:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack message
        uses: 8398a7/action-slack@v3.16.2
        with:
          payload: | {
            text : "데일리 보고"
          }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          CHANEEL_ID: ${{secrets.CHANNEL_ID}}
