name: Send Slack Daily Report

on:
  schedule:
    - cron: "46 17 * * 1-5"

jobs:
  send_slack_message:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack message
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{secrets.CHANNEL_ID}}
          payload: |
            {
                "text": "GitHub Action build result",
                "blocks": [
                {
                    "type": "section",
                    "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result:"
                    }
                }
                ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_WEBHOOK_URL }}

        if: always()
