name: Send Slack Daily Report

on:
  push:
    branches:
      - main
  schedule:
    - cron: "00 17 * * 1-5"

jobs:
  send_slack_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install # 의존성 설치

      - name: Get today's date
        id: get_date
        run: |
          echo "DATE=$(node ./src/calcToday.js)" >> $GITHUB_ENV

      - name: notify slack
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          #   channel-id: ${{ secrets.CHANNEL_ID }}
          channel-id: C07KW7U17MJ
          #   payload: '{"text": "테스트"}'
          payload: '{"text": "${{ env.DATE }} 데일리보고"}'

        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

        if: always()
